---
language: python
python: 3.6.5
services: docker

env:
  global:
    - ROLE_NAME: aws-inspector-agent
  matrix:
    - MOLECULE_DISTRO: amazonlinux

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $ROLE_NAME leppikallio.$ROLE_NAME
  - cd leppikallio.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
