---
- name: Converge
  hosts: all
  become: true

  vars:
    aws_inspector_role_test_mode: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Amazon'
      changed_when: false

  roles:
    - role: aws-inspector-agent
